import Preview from "../components/Preview";
import { trackPageView } from "../utils/goat";
import { useViewCount } from "../hooks/useViews";
import GiscusComments from "../components/GiscusComments";
import { useEffect } from "react";

const Blog1: React.FC = () => {

  const { views, loading } = useViewCount("blog-the-crisis-of-tomorrow");

  useEffect(() => {
    trackPageView("blog-the-crisis-of-tomorrow");
  }, []);

  return (
    <main className="p-6 md:p-10 max-w-7xl mx-auto">
      {/* Title Section */}
      <section className="max-w-2xl mb-12">
        <h1 className="text-4xl md:text-5xl font-bold typing-animation leading-tight">
          The Crisis of Tomorrow.
        </h1>

        <p className="mt-3 text-muted">
          by{" "}
          <a
            href="https://github.com/endan-criso"
            target="_blank"
            rel="noopener noreferrer"
            className="text-primary hover:underline"
          >
            Endan Criso
          </a>{" "}
          on <time dateTime="2025-02-24">24 Feb 2025</time>
        </p>
          <span className="flex items-center gap-1">
            {loading ? "..." : views?.toLocaleString() ?? "0"} views
          </span>
      </section>

      {/* Introduction */}
      <section>
        <h2 className="text-2xl font-bold mb-4 underline underline-offset-4">Introduction</h2>

        <p className="leading-7 text-muted mb-10">
          <span className="underline underline-offset-2 text-text">
            "Humans were the most intelligent creature in the universe."
          </span>{" "}
          That’s what we had been taught. But ladies and gentlemen, welcome to a
          new era—where AI and machines do our work while we slowly lose the very
          thing that separated us from animals:{" "}
          <span className="font-bold text-text">thinking</span>.
          <br />
          <br />
          Thinking and learning require patience and hard work. These are the
          forces that pushed mankind from wheels to self-driving cars, from
          calculators to supercomputers, from simple code to systems that can now
          write their own.
          <br />
          <br />
          Today, we discuss the effects of using AI in our daily lives.
        </p>
      </section>

      {/* Global Effect */}
      <section>
        <h2 className="text-2xl font-bold mb-4 underline underline-offset-4">Global Effect</h2>

        <p className="leading-7 text-muted">
          To make these machines work, we don’t just need code—we need an entire
          invisible world of infrastructure humming behind every prompt. Each
          question travels to massive data centers filled with high-performance
          processors consuming significant electricity and generating intense
          heat that must be constantly cooled.
          <br />
          <br />
          A single interaction feels effortless. Multiply that by millions of
          users every second, and the demand becomes enormous—energy grids
          powering servers day and night, cooling systems circulating vast
          amounts of water, and global networks delivering responses in
          milliseconds.
        </p>

        {/* Preview + Stats */}
        <div className="flex flex-col lg:flex-row mt-10 gap-8">
          <Preview
            image="https://www.csemag.com/wp-content/uploads/2025/03/CSE2405_MAG_HVAC_Figure_7_slider-e1716927060367.jpg"
            title="Data Center Cooling Systems"
            description="Modern AI data centers use chilled-water loops, CRAH units, and evaporative cooling to remove heat generated by GPU clusters."
            url="https://www.brookings.edu/articles/ai-data-centers-and-water/"
          />

          <div>
            <h3 className="text-xl font-bold mb-4">On Average:</h3>

            <ul className="list-disc list-inside space-y-4 text-muted leading-7">
              <li>
                <a
                  href="https://www.pewresearch.org/short-reads/2025/10/24/what-we-know-about-energy-use-at-us-data-centers-amid-the-ai-boom/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="underline underline-offset-2 hover:text-text"
                >
                  Data centers used 183 TWh of electricity in 2024 — ~4% of U.S.
                  power use.
                </a>
              </li>

              <li>
                <a
                  href="https://www.eli.org/vibrant-environment-blog/ais-cooling-problem-how-data-centers-are-transforming-water-use"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="underline underline-offset-2 hover:text-text"
                >
                  A typical data center may use ~300,000 gallons of water per
                  day.
                </a>
              </li>

              <li>
                <a
                  href="https://www.theguardian.com/technology/2025/dec/18/2025-ai-boom-huge-co2-emissions-use-water-research-finds"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="underline underline-offset-2 hover:text-text"
                >
                  AI systems could produce up to 80 million tonnes of CO₂.
                </a>
              </li>

              <li>
                <a
                  href="https://arxiv.org/abs/2503.05804"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="underline underline-offset-2 hover:text-text"
                >
                  Training a single large model can emit hundreds of tons of CO₂.
                </a>
              </li>

              <li>
                <a
                  href="https://www.wired.com/story/could-we-put-ai-data-centers-in-space/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="underline underline-offset-2 hover:text-text"
                >
                  By 2028, AI servers may use energy comparable to 22% of U.S.
                  households.
                </a>
              </li>
            </ul>
          </div>
        </div>

        <p className="mt-12 text-lg md:text-xl font-bold">
          The real question is: Are we willing to let future generations face
          shortages of basic resources for the convenience we enjoy today?
        </p>
      </section>

      {/* Mental Effect */}
      <section>
        <h2 className="text-2xl font-bold mt-10 underline underline-offset-4">The Mental Effect of AI</h2>

        <p className="leading-7 text-muted mt-10">
          God has given us a powerful tool: our minds. It’s the ability to think, create, visualize, and solve problems that has allowed us to build civilizations, explore the universe, and create art. But what happens when we outsource this gift to machines? I'm sure all of us have experienced the convenience of asking AI to write an email, generate a code snippet, or even asking about relationship advice. It’s like having a super-smart assistant at our fingertips. But over time, this convenience can lead to a dangerous dependency. When we rely on AI for answers, we stop exercising our own critical thinking skills. We become passive consumers of information rather than active thinkers. This can lead to a decline in creativity, problem-solving abilities, and even memory retention. If we let AI do all the thinking for us, we risk losing the very thing that makes us human: our ability to think deeply and independently.
          <br/>
          <br/>
          People in 80s and 90s had beautiful minds that can store 1000 phone numbers, remember directions, and solve complex problems with just limited access to information. But with the rise of smartphones 2000s has lost there memory retention capabilities, and now with the rise of AI era, we are losing our critical thinking skills too. It's too sad to see but it's was really happening. We are becoming more and more dependent on AI for even the simplest tasks like planning your day, cross checking your work, and even making decisions. It may look silly but i started to experience it after using LLMs (Large Language Models) for a while. Now experiencing a blockage in my brain like self-doubt and lack of confidence in my own thinking abilities. It feels like we are reverting back rather than evolving.
          <br/>
          <br/>
          <a href="https://www.nytimes.com/2025/11/06/technology/personaltech/ai-social-media-brain-rot.html#after-bottom" target="_blank" rel="noopener noreferrer" className="underline underline-offset-2 hover:text-text">
          <span className="font-bold text-text text-red">Note: Not only AI software like Instagram, Tik Tok are designed to be addictive and keep users engaged for longer periods of time. Which will lead to a loss of focus and productivity in the long run.</span></a>

        </p>
      </section>

      {/* Companies Focus */}
      <section>
        <h2 className="text-2xl font-bold mt-10 underline underline-offset-4">Economy Effect</h2>
        <p className="leading-7 text-muted mt-10">
          Inorder to understand the effect first we need to understand about how money works. Money is a medium of exchange that allows us to trade goods and services. It's a cycle that keeps the economy moving. When we buy something, we give money to the seller, who then uses that money to pay their employees, who then use that money to buy things for themselves, and so on. This cycle creates jobs, generates income, and drives economic growth. 
          But when sellers start using AI to automate their work, they can reduce their costs and increase their profits by replacing those employees with machines. What will the employees do now if they lose their jobs? They will have less money to spend, which means they will buy less things, which means the sellers will make less money, which means they will have to lay off more employees, and the cycle continues. This creates a vicious cycle of unemployment and economic decline.
          <br/>
          <br/>
          You can say that companies will save money and new jobs will be created in the AI industry, but the reality is that the number of jobs last due to AI automation will far exceed the number of jobs created in the AI industry. This will lead to a significant increase in unemployment and economic inequality. The rich will get richer while the poor will get poorer, and the gap between them will continue to widen.
        </p>  

      </section>

      {/* DO companies care */}
      <section>
        <h2 className="text-2xl font-bold mt-10 underline underline-offset-4">Does these companies care?</h2>
        <p className="leading-7 text-muted mt-10">
          Companies need to make profits to survive and pleased their shareholders. They will always prioritize their profits over the well-being of their employees and the society. They will use AI to automate their work and reduce their costs, regardless of the consequences. They will not care about the unemployment and economic inequality that they are creating, as long as they are making money. They will continue to push for more automation and AI integration, without any regard for the human cost.
          <br/>
          <br/>
          You may have thought why there are given AI tools and resources for free? It's because they want the humanity to taste the convenience of AI and get addicited to it, so when the time comes for subscriptions and paid services, they know people will surely pay for it because they are already addicted to it. It's a smart strategy to create a dependency on their products and services, so that they can monetize it in the long run. They will continue to innovate and improve their AI technology, making it even more indispensable for our daily lives, and we will have no choice but to rely on it, even if it means sacrificing our own thinking abilities and economic stability.
        </p>  

      </section>

      <section>
        <h2 className="text-2xl font-bold mt-10 underline underline-offset-4">Conclusion</h2>
        <p className="leading-7 text-muted mt-10">
         Is there anyway to stop this crisis? "hypothesis: Genocide of AI we need to stop using AI and services for everything and start using our own minds again. Use the traditional google search instead of asking AI, write your own code instead of asking AI to write it for you, and try to solve problems on your own instead of asking AI for solutions." We need to break the dependency on AI and start using our own minds again. We need to be mindful of the consequences of our actions and make conscious choices about how we use technology. We need to prioritize our own well-being and the well-being of future generations over the convenience of AI. We need to take responsibility for our own thinking and not let machines do it for us.
         because if we continue down this path, companies like this become a monopoly and control everything, and we will be at their mercy. They will dictate how we live our lives, what we think, and how we interact with the world. We need to wake up before it's too late and take back control of our own minds and our own lives.
         <br/>
         <br/>
         The crisis of tomorrow is not just about the environment, the economy, or our mental health. It's about our very humanity. We need to ask ourselves: What kind of future do we want to create? Do we want a future where machines do all the thinking for us, or do we want a future where we continue to evolve and grow as human beings? The choice is ours, but we need to act now before it's too late.
        </p>  
      </section>


      <section className="mt-12">
        <h2 className="text-2xl font-bold mb-4 underline underline-offset-4">References</h2>

        <ul className="list-disc list-inside space-y-2 text-muted leading-7">
          <li>
            <a
              href="https://playdead.com/games/inside/"
              target="_blank"
              rel="noopener noreferrer"
              className="underline underline-offset-2 hover:text-text"
            >
             Please take a look at this game called "Inside" by Playdead. A future more we look like. 
            </a>
          </li>
          <li>
            <a
              href="https://www.theguardian.com/technology/2026/feb/23/sam-altman-openai-energy-use-datacenters"
              target="_blank"
              rel="noopener noreferrer"
              className="underline underline-offset-2 hover:text-text"
            >
             Sam Altman defends AI’s energy toll by saying it also takes a lot to ‘train a human’
            </a>
          </li>
        </ul>
        </section>


    <section className="mt-16 border-t pt-10">
      <h2 className="text-2xl font-bold mb-6">Discussion</h2>
      <GiscusComments />
    </section>

    </main>
  );
};

export default Blog1;